# Generated by Django 4.2.8 on 2024-05-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_deposits',
            field=models.ManyToManyField(blank=True, related_name='users', to='finance.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_savings',
            field=models.ManyToManyField(blank=True, related_name='users', to='finance.savingproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
